# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'breaktheice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for breaktheice

  pod 'Firebase/Messaging'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

end
